tecnologia = [['Qual das seguintes é uma linguagem de codificação também conhecida como um termo para café?', ['Java', 'Joe', 'CoffeeBean'], 'Java'],
  ['O que significa a sigla “www” na internet?', ['World wide web', 'Web world wide', 'Web wide world'], 'World wide web'],
  ['Qual foi o primeiro tweet da história?', ['Olá, twitter.', 'Olá, mundo.', 'Estou preparando meu twitter.'], 'Estou preparando meu twitter.'], 
  ['Qual foi a duração do primeiro vídeo do Youtube?', ['3 minutos', '1 minuto', '18 segundos'], '18 segundos'], 
  ['Qual foi a primeira rede social da história da internet?', ['Classmate', 'MySpace', 'Orkut'], 'Classmate'],
  ['Quando foi criado o primeiro smartphone da história?', ['1994', '2000', '1998'], '1994'],
  ['Qual a resolução de uma imagem Full HD?', ['1920 x 1080', '1280 x 720', '2560 x 1440'], '1920 x 1080'],
  ['Quantos bits cabem em um byte?', ['8 bits', '1 bit', '12 bits'], '8 bits'],
  ['Como é medida a qualidade de uma impressora?', ['Alfabeto por polegada', 'Pontos por polegada', 'Marcado por polegada'], 'Pontos por polegada'],
  ['Quem desenvolveu o Yahoo?', ['Dennis Ritchie & Ken Thompson', 'David Filo & Jerry Yang', 'Vint Cerf & Robert Kahn'], 'David Filo & Jerry Yang'],
  ['Qual foi o primeiro mecanismo de busca na internet', ['Google', 'Archie', 'Nemo'], 'Archie'],
  ['Número de bits usados pelo endereço IPv6', ['32 bits', '64 bits', '128 bits'], '128 bits'],
  ['Qual é o primeiro navegador da Web inventado em 1990', ['Internet Explorer', 'Mosaic', 'Nexus'], 'Nexus'],
  ['Qual dos seguintes não é um sistema operacional', ['DOS', 'macOS', 'C'], 'C'],
  ['1024 bits é igual a quantos bytes', ['1Byte', '128Byte', '32Byte'], '128Byte'],
  ['.gif é uma extensão de', ['Arquivo de imagem', 'Arquivo de vídeo', 'Arquivo de áudio'], 'Arquivo de imagem'],
  ['Onde está localizada a sede do escritório da Microsoft', ['Texas', 'NewYork', 'Washington'], 'Washington'],
  ['O sistema operacional Mac é desenvolvido por qual empresa', ['IBM', 'Apple', 'Microsoft'], 'Apple'],
  ['Qual dos seguintes não é um software de gerenciamento de banco de dados', ['COBOL', 'Oracle', 'Sybase'], 'COBOL'],
  ['Um firewall é usado para', ['Segurança', 'Transmissão de dados', '32Byte'], 'Segurança'],
  ['Qual dos seguintes lançou o primeiro serviço de áudio da Índia "Suno"?', ['Netflix', 'Google', 'Audible'], 'Audible'],
  ['Cientistas de qual instituto desenvolveram o maior chip de computador de todos os tempos usando nanotubos de carbono (CNT)-RV16XNano?', ['Yale', 'MIT', 'Harvard'], 'MIT'],
  ['Facebook lança criptomoeda que permite aos usuários fazer transações financeiras em todo o mundo. É nomeado como ', ['Dobil', 'Libra', 'Cryco'], 'Libra'],
  ['AntBot é o primeiro robô ambulante a ter recursos de navegação sem GPS ou mapeamento. Quem o projetou?', ['NREC', 'Grupo de Pesquisa de Sistemas Adaptativos da Universidade de Hertfordshire', 'CNRS & AMU'], 'CNRS & AMU'],
  ['Qual protocolo fornece facilidade de e-mail entre diferentes hosts', ['FTP', 'TELNET', 'SMTP'], 'SMTP'],
  ['A arquitetura básica de um computador foi projetada por', ['Von Neumann', 'Charles Babbage', 'Blaise Pascal'], 'Von Neumann'],
  ['Qual das seguintes memórias é volátil?', ['EPROM', 'RAM', 'ROM'], 'RAM'],
  ['O formato AVI (Audio Video Interleave) foi desenvolvido por?', ['IBM', 'Microsoft', 'Adobe'], 'Microsoft'],
  ['Qual comando é usado para remover um diretório no Linux?', ['rdir', 'remove', 'rmdir'], 'rmdir'],
  ['Em um aplicativo Javascript, qual função pode ser usada para enviar mensagens para usuários solicitando uma entrada de texto?', ['Prompt()', 'Display()', 'GetOutpu()'], 'Prompt()'],
  ['Tegra, Tesla, GeForce e nForce são séries para chipsets integrados de qual empresa?', ['AMD', 'Redpine', 'NVIDIA'], 'NVIDIA'],
  ['Qual foi o predecessor da Wikipedia?', ['WikiLeaks', 'Nupedia', 'Desciclopédia'], 'Nupedia'],
  ['Em que ano o sinal "@" foi escolhido pela primeira vez para seu uso no endereço de e-mail', ['1972', '1977', '1980'], '1972'],
  ['Qual é o número máximo de partições primárias que podem ser criadas em um disco rígido', ['2', '4', '3'], '4'],
  ['O número total de pinos em uma porta paralela tradicional é', ['5', '14', '25'], '25'],
  ['O que o FLOPS mede?', ['Operações de Ponto Flutuante', 'Frequência de Oscilação', 'Tentativas de Acesso Estrangeiro'], 'Operações de Ponto Flutuante'],
  ['JSON é frequentemente visto como uma alternativa para qual idioma?', ['PHP', 'XML', 'HTML'], 'XML'],
  ['Qual pessoa seleciona e configura computadores para uma organização?', ['Administrador de sistema', 'Analista de sistema', 'Webmaster'], 'Analista de sistema'],
  ['UTF-8 e UTF-16 são versões diferentes de que tipo de codificação de caracteres?', ['ASCII', 'Unicode', 'Binary'], 'Unicode'],
  ['<body> e <head> são exemplos de quê?', ['tags HTML', 'funções HTML', 'formatos HTML'], 'tags HTML'],
  ['ECC é um tipo de componente de hardware?', ['CPU', 'SSD', 'RAM'], 'RAM'],
  ['El Capitan foi um refinamento de qual versão anterior do sistema operacional de desktop da Apple?', ['Sierra', 'High Sierra', 'Yosemite'], 'High Sierra'],
  ['Qual tecnologia do Windows foi desenvolvida para aproveitar a GPU de um computador?', ['NTFS', 'WDDM', 'ActiveX'], 'WDDM'],
  ['Uma interface de linha de comando também pode ser chamada de quê?', ['GUI', 'Shell', 'NUI'], 'Shell'],
  ['Quantos terminais tem um diodo?', ['2', '1', '3'], '2'],
  ['Um servidor de arquivos é um exemplo de quê?', ['Saas', 'NAS', 'BIOS'], 'NAS'],
  ['Qual das seguintes afirmações sobre o tipo de dados Enum é verdadeira?', ['É a maneira mais eficiente de armazenar inteiros.', 'Não pode armazenar strings.', 'Pode conter uma lista de valores específicos.' ], 'Pode conter uma lista de valores específicos.'],
  ['Para que serve um URI?', ['Ele fornece uma maneira padrão de localizar arquivos.', 'Evita que os arquivos sejam excluídos acidentalmente.', 'Ele traduz dados de arquivos binários em texto simples.'], 'Ele fornece uma maneira padrão de localizar arquivos.'],
  ['Grandes quantidades de dados usados em configurações corporativas também são chamadas de quê?', ['Fat data', 'Big data', 'Bulk Data'], 'Big data'],
  ['DNS traduz nomes de domínio em que tipo de endereço?', ['Localhost', 'Hostname', 'IP Address'], 'IP Address'],
  ['Qual sistema operacional é usado como base da maioria dos sistemas operacionais de código aberto?', ['MacOS', 'Linux', 'Windows'], 'Linux'],
  ['Qual dos seguintes é normalmente armazenado na ROM de um dispositivo de hardware?', ['Freeware', 'Firmware', 'Shreware'], 'Firmware'],
  ['Que tipo de tecnologia a organização MPEG desenvolve e mantém?', ['Formatos de imagem sem perda', 'Formatos de vídeo compactados', 'Protocolos de mídia de streaming'], 'Formatos de vídeo compactados'],
  ['Em vez de pixels, gráficos vetoriais são compostos de quê?', ['Pontos', 'Caminhos', 'Blocos'], 'Caminhos']]

astronomia = [['Qual planeta do nosso Sistema Solar é conhecido como a "Estrela d`Alva"?', ['Vênus', 'Mercúrio', 'Urano'], 'Vênus'],
    ['Como é chamado o corpo celeste, decorrente de uma explosão de uma supernova, com um intenso campo magnético?', ['Magnetar', 'Anã Branca', 'Buraco Negro'], 'Magnetar'],
    ['Qual o nome das duas estrelas mais brilhantes da constelação de Gêmeos?', ['Prócion e Altair', 'Póllux e Castor', 'Antares e Arcturus'], 'Póllux e Castor'],
    ['Qual o nome do centro de um buraco negro de onde a luz é incapaz de sair?', ['Singularidade', 'Horizonte de Eventos', 'Centro gravitacional'], 'Horizonte de Eventos'],
    ['Qual o planetóide mais próximo do planeta Terra?', ['Hauméia', 'Plutão', 'Ceres'], 'Ceres'],
    ['Como se chama o corpo celeste que se tivesse mais um pouco de massa se transformava em uma estrela?', ['Anã branca', 'Anã marrom', 'Anã cinza'], 'Anã marrom'],
    ['As estrelas mais quentes do universo tem a coloração...', ['Azul', 'Vermelha', 'Branca'], 'Azul'],
    ['Qual é o nome do buraco negro mais próximo do planeta Terra?', ['Phoenix C-44', 'Cygnus X-1', 'Haley'], 'Cygnus X-1'],
    ['O Sistema Solar possui quantos planetas oficialmente?', ['8', '6', '10'], '8'],
    ['Quem é responsável pela formação das marés?', ['O vento', 'A lua', 'A camada de ozônio'], 'A lua'],
    ['Existe água em Marte, o "Planeta Vermelho"?', ['Ехіѕtе nãо ѕó еm еѕtаdо ѕólіdо, mаѕ tаmbém еm еѕtаdо líquіdо.', 'Аіndа nãо fоі еnсоntrаdа nеnhumа еvіdênсіа, ареѕаr dаѕ várіаѕ tеntаtіvаѕ.', 'Nãо ехіѕtе.'], 'Ехіѕtе nãо ѕó еm еѕtаdо ѕólіdо, mаѕ tаmbém еm еѕtаdо líquіdо.'],
    ['Qual o veículo espacial mais rápido?', ['Qualquer foguete.', 'Qualquer ônibus espacial.', 'New Horizons, veículo da NASA.'], 'New Horizons, veículo da NASA.'],
    ['Como é o departamento médico da Estação Espacial Internacional?', ['Рrіmіtіvо, соmо dа ріѕсіnа dе um сlubе.', 'Futurіѕtа, іguаl аоѕ fіlmеѕ dе fісçãо сіеntífіса.', 'Ѕuреr соmрlеtо, еquіvаlеntе à um hоѕріtаl раrtісulаr.'], 'Рrіmіtіvо, соmо dа ріѕсіnа dе um сlubе.'],
    ['Como se chama um aglomerado de estrelas?', ['Buraco negro', 'Constelação', 'Planetoide'], 'Constelação'],
    ['Qual o satélite natural do planeta Terra?', ['Sol', 'Lua', 'Marte'], 'Lua'],
    ['De fato o que é uma estrela cadente?', ['Meteorito', 'Poeira cósmica', 'Estrela anã'], 'Meteorito'],
    ['Qual foi o ano que o homem pisou na Lua pela primeira vez?', ['1969', '1976', '1964'], '1969'],
    ['Por que a Terra é azul?', ['Reflete a Lua', 'Porque a atmosfera é neutra', 'Por causa do gás Ozônio'], 'Por causa do gás Ozônio'],
    ['Qual o maior planeta do Sistema Solar?', ['Marte', 'Terra', 'Júpiter'], 'Júpiter'],
    ['Pela ordem qual é o planeta cuja órbita fica entre Mercúrio e a Terra?', ['Marte', 'Saturno', 'Vênus'], 'Vênus'],
    ['Qual é o planeta do Sistema Solar que possui mais satélites?', ['Urano', 'Jupiter', 'Saturno'], 'Jupiter'],
    ['Io é um satélite natural de qual planeta?', ['Júpiter', 'Saturno', 'Vênus'], 'Júpiter'],
    ['O Cinturão de Asteróides localiza-se entre as órbitas de quais planetas?', ['Urano e Saturno', 'Marte e Júpiter', 'Júpiter e Urano'], 'Marte e Júpiter'],
    ['Qual a temperatura no núcleo do Sol?', ['5 milhões de graus Celsius.', '10 milhões de graus Celsius.', '15 milhões de graus Celsius.'], '15 milhões de graus Celsius.'],
    ['Quando o ciclo de vida das estrelas se inicia?', ['Com a junção de gases nas nebulosas', 'Quando elas querem', 'Ela simplesmente aparece no universo'], 'Com a junção de gases nas nebulosas'],
    ['O que são as nebulosas?', ['Sãо іmеnѕаѕ nuvеnѕ dе gáѕ соmроѕtаѕ роr Нélіо е Охіgênіо', 'Sãо іmеnѕаѕ nuvеnѕ dе gáѕ соmроѕtаѕ роr Ніdrоgênіо', 'Sãо іmеnѕаѕ nuvеnѕ dе gáѕ соmроѕtаѕ роr Нélіо е Ніdrоgênіо'], 'Sãо іmеnѕаѕ nuvеnѕ dе gáѕ соmроѕtаѕ роr Нélіо е Ніdrоgênіо'],
    ['O que leva uma estrela a sua morte?', ['O excesso de energia nuclear em seu núcleo', 'O excesso de Hidrogênio', 'O excesso de atomos'], 'O excesso de energia nuclear em seu núcleo'],
    ['Quanto maior for a massa de uma estrela:', ['Mais longa será sua vida', 'Menos será a sua luz', 'Mais breve será sua infância e sua vida adulta'], 'Mais breve será sua infância e sua vida adulta'],
    ['Durante a fase inicial de vida, a estrela esteve queimando hidrogênio no núcleo, em que ele se transforma?', ['Em oxigênio', 'Em massa', 'Em Hélio'], 'Em Hélio'],
    ['Qual planeta anão está localizado no cinturão de asteroides?', ['Haumea', 'Plutão', 'Ceres'], 'Ceres'],
    ['Onde estão localizados Haumea, Makemake e Pluto?', ['Nuvem de Oort', 'Cinturão de asteroides', 'Cinturão Kuiper'], 'Cinturão Kuiper'],
    ['Quais planetas anões foram visitados por sondas espaciais?', ['Apenas Plutão', 'Ceres e Plutão', 'Haumea e Pluto'], 'Ceres e Plutão'],
    ['Quantos planetas anões oficialmente reconhecidos existem no Sistema Solar?', ['20', '10', '5'], '5'],
    ['Por que Plutão não é mais considerado um planeta?', ['Não orbita o Sol', 'Não é grande o suficiente para se tornar esférico', 'Sua órbita se cruza com a de Netuno'], 'Sua órbita se cruza com a de Netuno'],
    ['Marte é o planeta que tem algumas possibilidades de haver vida,', ['Por causa de relativa sua "aparência" com a Terra.', 'Por causa de ser igual a Terra.', 'Por causa de ter água como a Terra.'], 'Por causa de relativa sua "aparência" com a Terra.'],
    ['Marte foi batizado em homenagem ao deus romano:', ['Da prosperidade.', 'Das estrelas.', 'Da guerra.'], 'Da guerra.'],
    ['Quem forneceu as primeiras informações sobre o Buraco Negro?', ['S. Chandrasekhar', 'Rutherford', 'Copérnico'], 'S. Chandrasekhar'],
    ['O planeta com maior duração do dia.', ['Vênus', 'Saturno', 'Terra'], 'Vênus'],
    ['Qual é o nome real da nossa "Lua"?', ['Solaris', 'Selene', 'Lua'], 'Lua']]

geografia = [['Qual continente é o segundo menor do mundo em tamanho, mas também tem a segunda maior população?', ['Europa', 'Africa', 'Ásia'], 'Europa'],
    ['O Grande Lago do Urso se estende por mais de 12.000 milhas quadradas. Em que país está localizado?', ['Canadá', 'Austrália', 'China'], 'Canadá'],
    ['Qual cidade é a única cidade do mundo localizada em dois continentes separados?', ['Viena', 'Salzburg', 'Istambul'], 'Istambul'],
    ['Qual é a montanha mais alta da Grã-Bretanha?', ['K2', 'Monte Everest', 'Ben Nevis'], 'Ben Nevis'],
    ['Qual oceano circunda o Havaí?', ['Pacífico', 'Atlântico', 'Índico'], 'Pacífico'],
    ['Que país não faz parte da Escandinávia?', ['Finlândia', 'Suécia', 'Dinamarca'], 'Finlândia'],
    ['Qual é a maior cidade e capital comercial do Sri Lanka?', ['Colombo', 'Kandy', 'Negombo'], 'Colombo'],
    ['Qual destes países NÃO faz parte do continente asiático?', ['Rússia', 'Suriname', 'Georgia'], 'Suriname'],
    ['Qual destas NÃO é uma cidade na Índia?', ['Islamabad', 'Ahmedabad', 'Ghaziabad'], 'Islamabad'],
    ['Qual país está completamente sem litoral pela África do Sul?', ['Botsuana', 'Lesoto', 'Zimbábue'], 'Lesoto'],
    ['Quantos países fazem fronteira com o Quirguistão?', ['6', '3', '4'], '4'],
    ['Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch está localizado em qual ilha galesa?', ['Anglesey', 'Barry', 'Caldei'], 'Anglesey'],
    ['Qual dessas cidades NÃO está na Inglaterra?', ['Edimburgo', 'Manchester', 'Southampton'], 'Edimburgo'],
    ['Qual destas NÃO é uma placa tectônica real?', ['Placa Atlântica', 'Placa de Nazca', 'Placa Eurasiana'], 'Placa Atlântica'],
    ['Qual não é um país da África?', ['Guiana', 'Senegal', 'Libéria'], 'Guiana'],
    ['Qual estado dos Estados Unidos é o menor?', ['Rhode Island', 'Maine', 'Vermont'], 'Rhode Island'],
    ['Em um mapa do metrô de Londres, qual é a cor da Circle Line?', ['Verde', 'Amarelo', 'Azul'], 'Amarelo'],
    ['Qual é a capital do Peru?', ['Lima', 'Santiago', 'Montevidéu'], 'Lima'],
    ['O Principado de Sealand é uma micronação não reconhecida na costa de que país?', ['Austrália', 'Reino Unido', 'Argentina'], 'Reino Unido'],
    ['Quantos países estão dentro do Reino Unido?', ['4', '5', '7'], '4'],
    ['Qual é a maior cidade de Marrocos?', ['Casablanca', 'Rabata', 'FÉ'], 'Casablanca'],
    ['Qual é o nome da capital da Turquia?', ['Bursa', 'Ismir', 'Ancara'], 'Ancara'],
    ['Kuala Lumpur é a capital de qual país?', ['Malásia', 'Tailândia"', 'Cingapura'], 'Malásia'],
    ['Qual destes países está localizado mais longe do Mar da China Meridional?', ['Bangladesh', 'Vietnã', 'Filipinas'], 'Bangladesh'],
    ['Qual é a capital da Groenlândia?', ['Sisimut', 'Nuuk', 'Narsak'], 'Nuuk'],
    ['O Lago Titicaca está localizado entre quais duas nações?', ['Peru e Bolívia', 'México e Estados Unidos', 'Índia e Bangladesh'], 'Peru e Bolívia'],
    ['Os Alpes são uma cadeia de montanhas em qual continente?', ['Ásia', 'Europa', 'África'], 'Europa'],
    ['A Groenlândia faz parte de qual reino?', ['Noruega', 'Dinamarca', 'Suécia'], 'Dinamarca'],
    ['Qual país é o segundo maior do mundo em área?', ['Canadá', 'Rússia', 'China'], 'Canadá'],
    ['Qual país a Áustria não faz fronteira?', ['Eslováquia', 'França', 'Suíça'], 'França'],
    ['Qual é a capital da Jamaica?', ['Kingston', 'Bridgetown', 'Porto Príncipe'], 'Kingston']]

curiosidade = [['Qual a temperatura necessária para a gasolina congelar?', ['-100 graus centigrados', '-117,5 graus centigrados', 'Nunca congela'], 'Nunca congela'],
    ['Qual o nome do presidente do Brasil que ficou conhecido como Jango?', ['Getúlio Vargas', 'João Figueiredo', 'João Goulart'], 'João Goulart'],
    ['Qual o livro mais vendido no mundo a seguir à Bíblia?', ['O Senhor dos Anéis', 'Dom Quixote', 'O Pequeno Príncipe'], 'Dom Quixote'],
    ['Quais os países que têm a maior e a menor expectativa de vida do mundo?', ['Japão e Serra Leoa', 'Austrália e Afeganistão', 'Itália e Chade'], 'Japão e Serra Leoa'],
    ['Qual a velocidade da luz?', ['299 792 458 (m/s)', '150 000 000 (m/s)', '199 792 458 (m/s)'], '299 792 458 (m/s)'],
    ['Qual o maior animal terrestre?', ['Baleia Azul', 'Elefante africano', 'Tubarão Branco'], 'Elefante africano'],
    ['As pessoas de qual tipo sanguíneo são consideradas doadores universais?', ['Tipo AB', 'Tipo A', 'Tipo O'], 'Tipo O'],
    ['Quem viveu, segundo a bíblia, 969 anos?', ['Noé', 'Matusalém', 'Abel'], 'Matusalém'],
    ['Quem pintou o teto da capela sistina?', ['Michelangelo', 'Rafael', 'Donatello'], 'Michelangelo'],
    ['Qual a primeira mulher a ganhar um prêmio Nobel?', ['Elizabeth Blackweel', 'Valentina Tereshkova', 'Marie Curie'], 'Marie Curie'],
    ['Qual a obra de arte mais cara já arrematada em um leilão?', ['O Sonho de Pablo Picasso', 'O Grito de Edvard Munch', 'Salvator Mundi de Leonardo da Vinci'], 'Salvator Mundi de Leonardo da Vinci'],
    ['Qual o país mais novo do mundo?', ['Sudão do Sul', 'Timor Leste', 'Montenegro'], 'Sudão do Sul'],
    ['Quem foi a primeira mulher a viajar para o espaço?', ['Kathryn D. Sullivan', 'Svetlana Savit', 'Valentina Tereshkova'], 'Valentina Tereshkova'],
    ['Quem foi a primeira mulher a se eleger presidente de um país?', ['Cristina Kirchner', 'Vigdís Finnbogadóttir', 'Dilma Roussef'], 'Vigdís Finnbogadóttir'],
    ['Qual o lugar mais profundo dos oceanos?', ['Fossa de Tonga', 'Fossa de Bentley', 'Fossa das Marianas'], 'Fossa das Marianas'],
    ['Quantos pares de costelas um ser humano, normalmente, possui?', ['12', '10', '8'], '12']]

